import { MyThemeProvider } from "@lms/components/providers/MyThemeProvider";
import "../styles/tailwind.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { MyQueryProvider } from "@lms/components/providers/MyQueryProvider";
import { MyLmsClientProvider } from "@lms/components/providers/MyLmsClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <MyThemeProvider>
          <MyLmsClientProvider>
            <MyQueryProvider>{children}</MyQueryProvider>
          </MyLmsClientProvider>
        </MyThemeProvider>
      </body>
    </html>
  );
}
